@startuml
title Architecture

node "FRONTEND" {
  [React App]
}

node "BACKEND" {
  [GraphQL Gateway]
  [Cat Service]
  database "Postgres" {
    [Cat Storage]
  }
}

[Cat Service] --> [GraphQL Gateway]
[Cat Service] - [Cat Storage]
[React App] --> [GraphQL Gateway] : GraphQL
[GraphQL Gateway] -left-> [React App]
[GraphQL Gateway] --> [Cat Service] : REST


@enduml
