@startuml

!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define primary_key(x) <b>x</b>
!define unique(x) <color:green>x</color>
!define not_null(x) <u>x</u>

hide methods
hide stereotypes

' entities

Table(Cat, "cat") {
primary_key(id) INTEGER
name TEXT
description TEXT
temperament TEXT
}


@enduml