version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '8000:8000'
      - '9229:9229'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432

  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=practicedocker